In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier , RandomForestClassifier
from sklearn.preprocessing import StandardScaler ,  LabelEncoder
from sklearn.metrics import accuracy_score ,  precision_score , recall_score
data=pd.read_csv(r"C:\Users\BHIMA SHANKAR\Downloads\Titanic-Dataset.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression , Lasso , Ridge
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import AdaBoostClassifier
data=pd.read_csv(r"C:\Users\BHIMA SHANKAR\Downloads\Titanic-Dataset.csv")
data.head(1000)
data["Age"].value_counts()
data.shape
data.isnull().sum()
data.Age.fillna(data.Age.mean())
data.Cabin.mode()[0]
data.Cabin.fillna(value=data.Cabin.mode()[0].split()[1],inplace=True)
encoder=LabelEncoder()
encoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVR
base_model = DecisionTreeClassifier()
x = data.drop(columns=['Survived'])
y = data.Survived
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
base_model
classifier = AdaBoostClassifier(random_state=42,estimator=base_model,n_estimators=100)
classifier

In [10]:
data["Age"].value_counts()

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [7]:
data.shape

(891, 12)

In [8]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
data.Age.fillna(data.Age.mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [ ]:
data.Cabin.mode()[0]

'B96 B98'

In [16]:
data.Cabin.fillna(value=data.Cabin.mode()[0].split()[1],inplace=True)

In [17]:
encoder=LabelEncoder()
encoder

LabelEncoder()

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVR
base_model = DecisionTreeClassifier()
x = data.drop(columns=['Survived'])
y = data.Survived
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
base_model
classifier = AdaBoostClassifier(random_state=42,estimator=base_model,n_estimators=100)
classifier

AdaBoostClassifier(estimator=DecisionTreeClassifier(), n_estimators=100,
                   random_state=42)

In [26]:
data.Sex=encoder.fit_transform(data.Sex)
data.Cabin=encoder.fit_transform(data.Cabin)
data.Embarked=encoder.fit_transform(data.Embarked)
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,48,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,82,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,48,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,56,2
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,48,2

In [28]:
std_scalar=StandardScaler()
data.Age=std_scalar.fit_transform(data[["Age"]])
data.Fare=std_scalar.fit_transform(data[["Fare"]])
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,-0.592481,1,0,A/5 21171,-0.502445,48,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,0.638789,1,0,PC 17599,0.786845,82,0
2,3,1,3,"Heikkinen, Miss. Laina",0,-0.284663,0,0,STON/O2. 3101282,-0.488854,48,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,0.407926,1,0,113803,0.420730,56,2
4,5,0,3,"Allen, Mr. William Henry",1,0.407926,0,0,373450,-0.486337,48,2

In [29]:
x= data.drop(columns="Survived")
y = data.Survived

In [30]:
x_train ,x_test ,y_train, y_test = train_test_split(x,y , random_state=42 , test_size=0.2)

In [31]:
base_model = DecisionTreeClassifier(max_depth=1 , random_state=42 )

In [32]:
base_model

DecisionTreeClassifier(max_depth=1, random_state=42)

In [33]:
classifier = AdaBoostClassifier(random_state=42 , estimator=base_model , n_estimators= 100)
classifier

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1,
                                                    random_state=42),
                   n_estimators=100, random_state=42)

In [42]:
classifier.fit(x_train , y_train)

ValueError: could not convert string to float: 'Partner, Mr. Austen'

In [41]:
pred = classifier.predict(x_test)

AttributeError: 'AdaBoostClassifier' object has no attribute 'n_classes_'